# Phishing Website Detection using Machine Learning

## Notebook 04: Feature Engineering

### Objective

The objective of this notebook is to prepare the cleaned phishing website dataset for machine learning by reducing feature redundancy and creating the final engineered dataset.

---

## 1. Import Libraries

Import the required libraries for feature engineering.

In [8]:
import pandas as pd
import numpy as np

## 2. Load the Cleaned Dataset

Load the cleaned dataset generated during the preprocessing stage.

In [2]:
df = pd.read_csv("../dataset/cleaned_phishing_dataset.csv")

df.head()

,num_dots_url,num_hyph_url,num_underline_url,num_slash_url,num_questionmark_url,num_equal_url,at_sign_url,num_and_url,num_exclamation_url,num_space_url,...,tilde_param,num_comma_param,num_plus_param,num_asterisk_param,num_dollar_param,num_percent_param,length_param,tld_in_param,num_param,phishing
0,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,5,1,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,2,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## 3. Separate Features and Target

Separate the input features and the target variable for feature engineering.

In [3]:
X = df.drop("phishing", axis=1)

y = df["phishing"]

print("Features :", X.shape)
print("Target :", y.shape)

Features : (4129, 74)
Target : (4129,)

## 4. Remove Highly Correlated Features

**Question:** Are there any highly correlated features that may provide redundant information?

Identify highly correlated feature pairs and remove one feature from each pair to reduce redundancy in the dataset.

In [15]:
X = df.drop("phishing", axis=1)
y = df["phishing"]

In [16]:
# First, calculate the correlation matrix.
corr_matrix = X.corr().abs()

# Extract only the upper triangle to avoid duplicate comparisons.
upper_triangle = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

In [17]:
# Find the features whose correlation is greater than 0.80.
features_to_drop = [
    column
    for column in upper_triangle.columns
    if any(upper_triangle[column] > 0.80)
]

X = X.drop(columns=features_to_drop)

print("Removed Features:")
for feature in features_to_drop:
    print("-", feature)

print(f"\nNumber of Features Removed: {len(features_to_drop)}")
print(f"Remaining Features: {X.shape[1]}")

Removed Features:
- num_and_url
- num_percent_url
- email_in_url
- length_dom
- num_space_path
- num_comma_path
- num_equal_file
- num_exclamation_file
- num_space_file
- num_comma_file
- num_plus_file
- num_percent_file
- num_underline_param
- num_equal_param
- num_and_param
- num_dollar_param
- length_param
- num_param

Number of Features Removed: 18
Remaining Features: 56

### Interpretation

- A correlation threshold of **0.80** was used to identify highly correlated feature pairs.
- One feature from each highly correlated pair was removed to reduce redundancy.
- Although features such as `length_dom` and `length_param` were removed, they were highly correlated with other retained features that capture similar information.
- The final dataset contains **56 features**, making it more compact while preserving the essential information for model building.

---

## 5. Create Final Engineered Dataset

**Question:** What does the final feature set look like after removing redundant features?

Combine the remaining features with the target variable to create the final engineered dataset for model development.

In [6]:
engineered_df = X.copy()

engineered_df["phishing"] = y

engineered_df.head()

,num_dots_url,num_hyph_url,num_underline_url,num_slash_url,num_questionmark_url,num_equal_url,at_sign_url,num_exclamation_url,num_space_url,tilde_url,...,at_sign_param,num_exclamation_param,num_space_param,tilde_param,num_comma_param,num_plus_param,num_asterisk_param,num_percent_param,tld_in_param,phishing
0,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,5,1,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,2,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Interpretation

- The final engineered dataset contains the remaining informative features after removing highly correlated features.
- This dataset will be used for training and evaluating machine learning models in the next notebook.

---

In [13]:
print(X.shape)
print(engineered_df.shape)

(4129, 56)
(4129, 57)

## 6. Save the Engineered Dataset

Save the final engineered dataset for use in the model building stage.

In [7]:
engineered_df.to_csv(
    "../dataset/engineered_phishing_dataset.csv",
    index=False
)

print("Engineered dataset saved successfully.")

Engineered dataset saved successfully.

## 7. Key Findings

- Highly correlated features were removed to reduce redundancy.
- The final dataset contains a more compact set of features.
- The engineered dataset is ready for machine learning model development.

## 8. Conclusion

The phishing website dataset was prepared for machine learning by removing redundant features and creating a final engineered dataset. This dataset will be used to build and evaluate classification models in the next notebook.